version: '3'

tasks:
  run:
    desc: Run application
    cmds:
      - uv run main.py
  check:
    desc: Run CI checks
    cmds:
      - task: lint
  lint:
    desc: Run lint
    cmds:
      - ruff check
