version: "3"

includes:
  scraper:
    taskfile: ./scraper/Taskfile.yaml
    dir: ./scraper

tasks:
  scrape:
    desc: Run web scrapers
    cmds:
      - task: scraper:run
  check:
    desc: Run CI checks
    cmds:
      - task: scraper:check
