version: "3"

includes:
  scraper:
    taskfile: ./scraper/Taskfile.yaml
    dir: ./scraper
  backend:
    taskfile: ./backend/Taskfile.yaml
    dir: ./backend
  frontend:
    taskfile: ./frontend/Taskfile.yaml
    dir: ./frontend

tasks:
  scrape:
    desc: Run web scrapers
    cmds:
      - task: scraper:run
  check:
    desc: Run CI checks
    cmds:
      - task: scraper:check
      - task: backend:check
      - task: frontend:check
